from enum import Enum


class TokenType(Enum):
    ID = 'ID'
    FUNCID = 'FUNCID'
    NUMBER = 'NUMBER'

    ELGIO = 'ELGIO'
    DECIMAL = 'DECIMAL'
    Z = 'Z'
    NEG = 'NEG'
    EXP = 'EXP'
    RESTO = 'RESTO'
    ENQUANTO = 'ENQUANTO'
    SE = 'SE'
    ENTAO = 'ENTAO'
    SENAO = 'SENAO'
    PARA = 'PARA'
    INICIO = 'INICIO'
    FIM = 'FIM'
    MAIOR = 'MAIOR'
    MENOR = 'MENOR'
    IGUAL = 'IGUAL'
    DIFERENTE = 'DIFERENTE'
    MIGUAL = 'MIGUAL'
    MIGUAL_CAP = 'MIGUAL_CAP'

    ASSIGN = 'ASSIGN'
    PLUS = 'PLUS'
    MINUS = 'MINUS'
    DIV = 'DIV'
    MULT = 'MULT'
    DOT = 'DOT'
    LPAREN = 'LPAREN'
    RPAREN = 'RPAREN'
    COMMA = 'COMMA'
